version: '3.8'

services:
  mongo-db:
    image: mongo:latest
    container_name: mongo-server
    ports:
      - "27017:27017"
    volumes:
      - /home/yar/Documents/projects/uber/mongo-db:/data/db
    networks:
      mongo-net:
        ipv4_address: 172.18.0.2

  mongo-admin:
    image: mongo-express:latest
    container_name: mongo-admin
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: 172.18.0.2
      ME_CONFIG_MONGODB_URL: mongodb://172.18.0.2:27017
    networks:
      mongo-net:
        ipv4_address: 172.18.0.3

networks:
  mongo-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
