version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-server
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

volumes:
  postgres-db: